blueprint:
  name: YLYK01YL - Yeelight Remote Control
  description: Simple action mapper to the Bluetooth based Yeelight Remote Control
  domain: automation
  source_url: https://github.com/samuelthng/t-house-blueprints/blob/main/ylyk01yl_yeelight_remote_control.yaml
  input:
    remote_entity:
      name: YLYK01YL Yeelight Remote Control Entity
      selector:
        entity:
          domain: sensor
          multiple: false
    single_on:
      name: Pressed "On"
      selector:
        action:
    single_off:
      name: Pressed "Off"
      selector:
        action:
    single_sun:
      name: Pressed "Sun"
      selector:
        action:
    single_m:
      name: Pressed "M"
      selector:
        action:
    single_plus:
      name: Pressed "+"
      selector:
        action:
    single_minus:
      name: Pressed "-"
      selector:
        action:
    long_on:
      name: Long pressed "On"
      selector:
        action:
    long_off:
      name: Long pressed "Off"
      selector:
        action:
    long_sun:
      name: Long pressed "Sun"
      selector:
        action:
    long_m:
      name: Long pressed "M"
      selector:
        action:
    long_plus:
      name: Long pressed "+"
      selector:
        action:
    long_minus:
      name: Long pressed "-"
      selector:
        action:
mode: single
trigger:
  - platform: state
    entity_id: !input remote_entity
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: !input remote_entity
        state: no press
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: single press on
        sequence: !input single_on
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: single press off
        sequence: !input single_off
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: single press sun
        sequence: !input single_sun
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: single press m
        sequence: !input single_m
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: single press +
        sequence: !input single_plus
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: single press -
        sequence: !input single_minus
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: long press on
        sequence: !input long_on
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: long press off
        sequence: !input long_off
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: long press sun
        sequence: !input long_sun
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: long press m
        sequence: !input long_m
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: long press +
        sequence: !input long_plus
      - conditions:
          - condition: state
            entity_id: !input remote_entity
            state: long press -
        sequence: !input long_minus
